[tool.black]
line-length=100
target-version=['py310']
skip-string-normalization=true
exclude='''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | env | venv | .venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''